print("----------------Numpy array-----------------------")
import numpy as np

a = np.array([1, 3, 5, 7, 9])
b = np.array([3, 5, 6, 7, 9])
c = a + b
print(' array a : ', a)
print(' array b :', b)
print(' array c=a+b : ', c)
input('--------------Shape of array c     PE----------')
print(np.shape(c))
# ("------------------ARRAY SIZE-----------------------")
input('--------------Press EnterArray size ------PE')
print(a.size)
# "---------------------ZEROS--of 2X 3 ----------------------")
input('-------Zeros of 2X3 size-----------PE')
print(np.zeros((2, 3)))
print("-----Arange- 10 serial no in consecutive order--------------------")
print(np.arange(10))
# "--------------------LINSPACE-----------------------")
input('----Generate linspace ------')
print(np.linspace(1., 4., 6))

# ("----------------random.random(shape)-----------------")
input('----generate random number of size 2 X 3 -------')
print(' ')
print(np.random.random((2, 3)))

# "--------------CHECKING THE TYPE of Array--------------")
input('-----Type of array---------')
print(type(a))

print("-----------NUMERIC ‘TYPE’ OF ELEMENTS-------------")
print(a.dtype)

print("----------------ARRAY COPY---------")
b = a.copy()
print(a)

print("--------------ARRAY INDEXING--------")
print(a[0])

print("---------------FILL--------------")
input('------Set all values in an array------PE-')
a.fill(0)
print(a)

# "--------------MATRIX--------------")
input('----creating matrix -------PE')
print('    ')
x = [[1, 2, 3], [3, 6, 9], [2, 4, 6]]
z = np.array(x)
print(z)

# ("------------Array Slicing----------")
input('-------Array slicing ---------PE')
a = np.array([[2, 3, 4, 7], [5, 4, 3, 2], [6, 3, 2, 1], [8, 3, 4, 7]])
print(a)
input('----column slicing --------PE')
print(a[:, 1:3])
input('------Row slicing----------PE')
print(a[1:3, :])
print("------------SUM FUNCTION-----------")
input('------sum of array elements ,min ,max,mean --------PE')
a = np.array([[1, 2, 3], [4, 5, 6]], float)
print(' array a  :', a)
print('sum of a :', sum(a))

print("-----------MIN--------------")

a1 = np.array([2., 3., 0., 1.])
print(a1)
print(a1.min(axis=0))
print("------------MAX--------------")
a2 = np.array([2., 1., 0., 3.])
print(a2.max(axis=0))
print("------------MEAN------------")
a3 = np.array([[1, 2, 3], [4, 5, 6]], float)
print('array : ', a3)
print('Mean :', a3.mean(axis=0))
# ("----------Random data in matrix--------")
input('-------Random data in matrix and sorting and transpose---------')
print(' ')
print(np.random.rand(5, 5))
print("---------SORTING----------")

arr = np.array([4.5, 2.3, 6.7, 1.2, 1.8, 5.5])
print(arr)
arr.sort()
print(arr)
print("-------------TRANSPOSE--------")
a4 = np.array([[1.0, 2.0], [4.0, 3.0]])
print(a4)
print(a4.transpose())

print("-------MEDIAN-----------")
# input('-----Median --------PE')
print(np.median(a4))
# ("----Logical Operators----")
input('-------Logical operations ----------')
a5 = np.array(((1, 2, 3, 4), (2, 3, 4, 5)))
b5 = np.array(((1, 2, 5, 4), (1, 3, 4, 5)))
print(a5 == b5)

print("--------BROADCASTING----------")
input('-----Broadcasting-------------')
a6 = np.array((0, 10, 20, 30))
b6 = np.array((0, 1, 2))
y = a6[:, None] + b6
print(y)
